updated the babel to latest version
Fixing the test cases
(babel plugin) Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
 
Require stack:
 
- /home/circleci/project/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
 
- /home/circleci/project/node_modules/@babel/preset-env/lib/index.js
 
- /home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js
 
- /home/circleci/project/node_modules/@babel/core/lib/config/files/index.js
 
- /home/circleci/project/node_modules/@babel/core/lib/index.js
 
- /home/circleci/project/node_modules/tsdx/dist/createRollupConfig.js
 
- /home/circleci/project/node_modules/tsdx/dist/createBuildConfigs.js
 
- /home/circleci/project/node_modules/tsdx/dist/index.js